services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: labeler
      POSTGRES_PASSWORD: labeler
      POSTGRES_DB: labeler
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labeler -d labeler"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app
      - appdata:/app/storage    # optional persistent data
    environment:
      DATABASE_URL: postgresql+psycopg://labeler:labeler@db:5432/labeler
    command: bash -lc "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -lc "npm ci || npm i && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
  appdata:
